name: expbottle
version: '1.0-SNAPSHOT'
main: dev.firestar.expbottle.Expbottle
api-version: '1.21.'
commands:
  expbottle:
    aliases:
      - bottle
      - xpbottle
    usage: /<command> <experience>
    description: Bottle je experience